#+BEGIN_COMMENT
.. title: Tied Ambition Scoring for 5 player Arcs
.. slug: tied-ambition-scoring-for-5-player-arcs
.. date: 2026-05-17 22:00:00 UTC+02:00
.. tags: arcs,boardgames
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

This post is about the scoring of tied tied ambitions in the board game
[[https://boardgamegeek.com/boardgame/359871/arcs][Arcs: Conflict & Collapse in the Reach]] and its upcoming expansion
[[https://boardgamegeek.com/boardgameexpansion/468034/arcs-lost-vaults-and-fated-leaders-expansion][Arcs: Lost Vaults & Fated Leaders]].

In Arcs, players win by collecting the most /power/ which they get by scoring
various /ambitions/. These ambitions are about having the highest count of a
specific resource type or other game marker.
The base game of Arcs supports two to four players, and each ambition yields
power points for the players scoring at the first and second place, with some
logic for dealing with tied players.

The upcoming expansion promises the possibility to include a fifth player, and
the print-and-play material from the [[https://www.kickstarter.com/projects/colewehrle/arcs-beyond-the-reach][Kickstarter campaign]] contains new ambition
markers that show power points awarded for the first, second *and* third place.
However, there are no official rules published (yet) about the assignment of
places in the case of ties when scoring ambitions. In the following, we show an
ambiguous situation and a possible generalisation of the existing rule.

* Base Game

The [[https://rules.buriedgiant.com/?product=arcs&locale=en-US&printing=p1#6.][rules for scoring]] state:

#+begin_quote
  The player who gets first place for the ambition gains the higher Power shown
  on all its ambition markers.

  The player who gets second place for it gains the lower Power shown on all its
  ambition markers.

  [...]

  *Ties.* On a tie for first place, all tied players get second place. (Other
  players do not place and gain no Power.) On a tie for second place, the tied
  players do not place and gain no Power.
#+end_quote

The rule covers all possibilities without ambiguity. I've produced tables
showing the result of all combinations with three and four players below.
Without loss of generality, we can assume that the players are sorted by the
relevant score, i.e., A ≥ B ≥ C ≥ D.

** Three players

| Scores    | Place: | A | B | C |
|-----------+--------+---+---+---|
| A > B > C |        | 1 | 2 | - |
| A > B = C |        | 1 | - | - |
| A = B > C |        | 2 | 2 | - |
| A = B = C |        | 2 | 2 | 2 |


** Four players

| Scores        | Place: | A | B | C | D |
|---------------+--------+---+---+---+---|
| A > B > C > D |        | 1 | 2 | - | - |
| A > B > C = D |        | 1 | 2 | - | - |
| A > B = C > D |        | 1 | - | - | - |
| A > B = C = D |        | 1 | - | - | - |
| A = B > C > D |        | 2 | 2 | - | - |
| A = B > C = D |        | 2 | 2 | - | - |
| A = B = C > D |        | 2 | 2 | 2 | - |
| A = B = C = D |        | 2 | 2 | 2 | 2 |

* Expansion: Lost Vaults & Fated Leaders

The expansion is supposed to support a fifth player and also comes with ambition
markers that show three values instead of the two before ("higher" and "lower").
Presumably, the three values are assigned to the players scoring at first,
second, and third place.
But what happens when some players are tied with their score?

Imagine the situation where two players (A & B) are tied for first place, while
C, D, and E score lower, i.e., A = B > C > D > E.
If we interpret the existing rules literally, then A & B would place second, and
all other players would not place.

Similarly, in a situation with a tie for second place, e.g., A > B = C > D > E,
only A would place first place, and other players get nothing.

But neither of these cases would make good use of the added third value on the
ambition marker, so let's try to adapt.

** Rule Generalisation

The rules as written can also be interpreted as follows

#+begin_quote
When players tie for a place, they all get points for the next lower place.
Players scoring lower also drop to the next place.
#+end_quote

This rule can be applied recursively, starting from the first place.

In our first example above (A = B > C > D > E), we would find that A & B tie for
first place, so they get points for second place. C would have placed second
place, but now gets third place. D and E would now get fourth and fifth place,
but the ambition markers don't provide points for these, so they get nothing.

In the second example (A > B = C > D > E), A scores first place (as before). B
and C are tied for the second place, so they now get points for the third place.
Again, D and E get nothing.

I've enumerated all combinations in the table below.

** Five Players

| Scores            | Place: | A | B | C | D | E |
|-------------------+--------+---+---+---+---+---|
| A > B > C > D > E |        | 1 | 2 | 3 | - | - |
| A > B > C > D = E |        | 1 | 2 | 3 | - | - |
| A > B > C = D > E |        | 1 | 2 | - | - | - |
| A > B > C = D = E |        | 1 | 2 | - | - | - |
| A > B = C > D > E |        | 1 | 3 | 3 | - | - |
| A > B = C > D = E |        | 1 | 3 | 3 | - | - |
| A > B = C = D > E |        | 1 | 3 | 3 | 3 | - |
| A > B = C = D = E |        | 1 | 3 | 3 | 3 | 3 |
| A = B > C > D > E |        | 2 | 2 | 3 | - | - |
| A = B > C > D = E |        | 2 | 2 | 3 | - | - |
| A = B > C = D > E |        | 2 | 2 | - | - | - |
| A = B > C = D = E |        | 2 | 2 | - | - | - |
| A = B = C > D > E |        | 2 | 2 | 2 | 3 | - |
| A = B = C > D = E |        | 2 | 2 | 2 | - | - |
| A = B = C = D > E |        | 2 | 2 | 2 | 2 | 3 |
| A = B = C = D = E |        | 2 | 2 | 2 | 2 | 2 |

